#!/usr/bin/env python3
"""Generate BitBake's checksummed crate list from Cargo.lock. Requires Python 3.11+."""

import argparse
from pathlib import Path
import sys
import tomllib


ROOT = Path(__file__).resolve().parents[1]
RECIPE_DIR = ROOT / "yocto/meta-spotflow/recipes-connectivity/spotflowd"
CRATES = RECIPE_DIR / "spotflowd-crates.inc"


def generated_crates():
    manifest = tomllib.loads((ROOT / "Cargo.toml").read_text())
    version = manifest["package"]["version"]
    recipes = list(RECIPE_DIR.glob("spotflowd_*.bb"))
    if len(recipes) != 1 or recipes[0].name != f"spotflowd_{version}.bb":
        raise ValueError(f"expected one recipe named spotflowd_{version}.bb")

    lock = tomllib.loads((ROOT / "Cargo.lock").read_text())
    if lock["version"] != 3:
        raise ValueError("Scarthgap's Cargo 1.75 requires lockfile format 3")

    crates = []
    for package in lock["package"]:
        source = package.get("source")
        if source is None:
            continue
        if source != "registry+https://github.com/rust-lang/crates.io-index":
            raise ValueError(f"unsupported dependency source: {source}")
        crates.append(package)
    crates.sort(key=lambda p: (p["name"], p["version"]))

    include = '# Generated by yocto/update-cargo.py from Cargo.lock.\n\nSRC_URI += " \\\n'
    for package in crates:
        include += f'    crate://crates.io/{package["name"]}/{package["version"]} \\\n'
    include += '"\n\n'
    for package in crates:
        include += (
            f'SRC_URI[{package["name"]}-{package["version"]}.sha256sum] = '
            f'"{package["checksum"]}"\n'
        )
    return include


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the crate list is out of date")
    args = parser.parse_args()
    content = generated_crates()
    if args.check:
        if not CRATES.exists() or CRATES.read_text() != content:
            sys.exit("outdated crate list; run python3 yocto/update-cargo.py")
    else:
        CRATES.write_text(content)
        print(f"updated {CRATES.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
